<?php
/*
 * RewardSciencesAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */

namespace RewardSciencesAPILib\Controllers;

use RewardSciencesAPILib\APIException;
use RewardSciencesAPILib\APIHelper;
use RewardSciencesAPILib\Configuration;
use RewardSciencesAPILib\Models;
use RewardSciencesAPILib\Exceptions;
use RewardSciencesAPILib\Http\HttpRequest;
use RewardSciencesAPILib\Http\HttpResponse;
use RewardSciencesAPILib\Http\HttpMethod;
use RewardSciencesAPILib\Http\HttpContext;
use Unirest\Request;

/**
 * @todo Add a general description for this controller.
 */
class Activities extends BaseController {

    /**
     * @var Activities The reference to *Singleton* instance of this class
     */
    private static $instance;
    
    /**
     * Returns the *Singleton* instance of this class.
     * @return Activities The *Singleton* instance.
     */
    public static function getInstance()
    {
        if (null === static::$instance) {
            static::$instance = new static();
        }
        
        return static::$instance;
    }

    /**
     * This endpoint lets you track the activities your users perform.
     * @param  integer     $userId            Required parameter: The ID of the user who is performing the activity.
     * @param  string      $activityType      Required parameter: The type of activity the user is performing. Example: 'purchased-a-product'
     * @param  integer     $price             Optional parameter: The price related to the activity, if any. Expressed in USD
     * @param  string      $recordId          Optional parameter: The ID for the record associated with the activity in your database.
     * @return mixed response from the API call
     * @throws APIException Thrown if API call fails
     */
    public function track (
                $userId,
                $activityType,
                $price = NULL,
                $recordId = NULL) 
    { 
        //check that all required arguments are provided
        if(!isset($userId, $activityType))
            throw new \InvalidArgumentException("One or more required arguments were NULL.");


        //the base uri for api requests
        $_queryBuilder = Configuration::$BASEURI;
        
        //prepare query string for API call
        $_queryBuilder = $_queryBuilder.'/activities';

        //process optional query parameters
        APIHelper::appendUrlWithQueryParameters($_queryBuilder, array (
            'user_id'       => $userId,
            'activity_type' => $activityType,
            'price'         => $price,
            'record_id'     => $recordId,
        ));

        //validate and preprocess url
        $_queryUrl = APIHelper::cleanUrl($_queryBuilder);

        //prepare headers
        $_headers = array (
            'user-agent'    => 'APIMATIC 2.0',
            'Accept' => Configuration::$accept,
            'Content-Type' => Configuration::$contentType,
            'Authorization' => sprintf('Bearer %1$s', Configuration::$oAuthAccessToken)
        );

        //call on-before Http callback
        $_httpRequest = new HttpRequest(HttpMethod::POST, $_headers, $_queryUrl);
        if($this->getHttpCallBack() != null) {
            $this->getHttpCallBack()->callOnBeforeRequest($_httpRequest);            
        }

        //and invoke the API call request to fetch the response
        $response = Request::post($_queryUrl, $_headers);

        //call on-after Http callback
        if($this->getHttpCallBack() != null) {
            $_httpResponse = new HttpResponse($response->code, $response->headers, $response->raw_body);
            $_httpContext = new HttpContext($_httpRequest, $_httpResponse);
            
            $this->getHttpCallBack()->callOnAfterRequest($_httpContext);            
        }

        //Error handling using HTTP status codes
        if (($response->code < 200) || ($response->code > 208)) { //[200,208] = HTTP OK
            throw new APIException("HTTP Response Not OK", $_httpContext);
        }

        return $response->body;
    }
        

}