<?php
/*
 * RewardSciencesAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */

namespace RewardSciencesAPILib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class. 
 */
class Configuration {
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://api.rewardsciences.com';

    /**
     * @todo Replace the $accept with an appropriate value
     */
    public static $accept = 'application/vnd.rewardsciences.v1+json';

    /**
     * @todo Replace the $contentType with an appropriate value
     */
    public static $contentType = 'application/json';

    /**
     * The OAuth 2.0 access token to be set before API calls
     * @var string
     */
    /**
     * @todo Replace the $oAuthAccessToken with an appropriate value
     */
    public static $oAuthAccessToken = 'TODO: Replace';

}
