<?php
/*
 * RewardSciencesAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */

namespace RewardSciencesAPILib;

use RewardSciencesAPILib\Controllers;

/**
 * RewardSciencesAPILib client class
 */
class RewardSciencesAPIClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct($accept = NULL, $contentType = NULL, $oAuthAccessToken = NULL)
    {
        Configuration::$accept = $accept ? $accept : Configuration::$accept;
        Configuration::$contentType = $contentType ? $contentType : Configuration::$contentType;
        Configuration::$oAuthAccessToken = $oAuthAccessToken ? $oAuthAccessToken : Configuration::$oAuthAccessToken;
    }
 
    /**
     * Singleton access to Rewards controller
     * @return Controllers\Rewards The *Singleton* instance
     */
    public function getRewards()
    {
        return Controllers\Rewards::getInstance();
    }
 
    /**
     * Singleton access to Users controller
     * @return Controllers\Users The *Singleton* instance
     */
    public function getUsers()
    {
        return Controllers\Users::getInstance();
    }
 
    /**
     * Singleton access to RewardCategories controller
     * @return Controllers\RewardCategories The *Singleton* instance
     */
    public function getRewardCategories()
    {
        return Controllers\RewardCategories::getInstance();
    }
 
    /**
     * Singleton access to Activities controller
     * @return Controllers\Activities The *Singleton* instance
     */
    public function getActivities()
    {
        return Controllers\Activities::getInstance();
    }
}